static const char *default_icon = "";

static const Icon icons[] = {
    {"Xfce4-terminal","  "},
    {"konsole","  "},
    {"Google-chrome","  "},
    {"Microsoft-edge","  "},
    {"firefox","  "},
    {"Nemo","  "},
    {"Code"," 󰨞 "},
    {"qtmv"," 󰟞 "},
    {"smplayer","  "},
    {"WizNote","  "},    
    {"obsidian","  "},    
    {"Blueman-manager","  "},
    {"Eog","  "},
    {"electron-netease-cloud-music"," 󰝚 "},
    {"yesplaymusic"," 󰝚 "},
    {"QQ","  "},
    {"Gnome-system-monitor"," 󰻠 "},
    {"com.xunlei.download"," 󱗆 "},
    {"Microsoft-edge-dev","  "},
    {"alixby3","  "},
    {"阿里云盘","  "},
    {"baidunetdisk","  "},
    {"wpsoffice"," 󰈭 "},
    {"Fsearch","  "},
    {"Gedit"," 󱞁 "},
    {"Gnome-terminal","  "},
    {"Clash-verge"," 󰄛 "},
    {"obs"," 󰻃 "},
    {"flameshot","  "},
    {"Pavucontrol","  "},
};