#!/usr/bin/env bash

STATUS=$(swaync-client -D)

toggle() {
    if [ $STATUS == "false" ]; then
        swaync-client -dn
    else
        swaync-client -df
        notify-send --urgency=low -i $HOME/tool/dnd.jpg "Do Not Disturb" "Do not Disturb has been turned off!"
    fi
}

icon() {
    if [ $STATUS == "false" ]; then
        echo "󱑙"
    else
        echo "󰍶"
    fi
}

status() {
    if [ $STATUS == "false" ]; then
        echo "Off"
    else
        echo "On"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
