#!/usr/bin/bash

MODE=$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | tail -1)

cpu_num=$( ls /sys/devices/system/cpu/ | grep -E "cpu[0-9]+"  | wc -l )

toggle() {
    if [[ "$MODE" == "ondemand" ]]; then
        while (( $cpu_num > 0 ));do
            cpu_num=$(( $cpu_num - 1 ))
            sudo cpufreq-set -c $cpu_num -g  performance
        done
    else
        while (( $cpu_num > 0 ));do
            cpu_num=$(( $cpu_num - 1 ))
            sudo cpufreq-set -c $cpu_num -g  ondemand
        done
    fi
}

icon() {
    if [[ "$MODE" == "ondemand" ]]; then
        echo "󰔢"
    else
        echo "󰔡"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--mode" ]]; then
    echo $MODE
elif [[ $1 == "--icon" ]]; then
    icon
fi